-- ─── Fera AI Solutions — Complete Database Schema ───
-- Includes: auth profiles, membership plans, payment requests,
-- memberships, bookings, analytics.

-- ══════════════════════════════════════════════════════
-- 0. EXTENSIONS
-- ══════════════════════════════════════════════════════
create extension if not exists "pgcrypto";

-- ══════════════════════════════════════════════════════
-- 1. USER PROFILES (syncs with auth.users)
-- ══════════════════════════════════════════════════════
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  is_admin boolean default false,
  role text default 'user' check (role in ('user', 'admin')),
  region text default 'local' check (region in ('local', 'global')),
  created_at timestamptz default now()
);

alter table profiles add column if not exists role text default 'user' check (role in ('user', 'admin'));
update profiles set role = 'admin' where is_admin = true;
update profiles set role = 'user' where role is null;

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    'user'
  );
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ══════════════════════════════════════════════════════
-- 2. MEMBERSHIP PLANS
-- ══════════════════════════════════════════════════════
create table if not exists membership_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text not null,
  price numeric(10,2) not null,
  currency text default 'USD',
  duration_days integer not null default 30,
  features jsonb default '[]',
  is_active boolean default true,
  created_at timestamptz default now()
);

-- ══════════════════════════════════════════════════════
-- 3. PAYMENT REQUESTS (screenshot uploads + PayPal)
-- ══════════════════════════════════════════════════════
create table if not exists payment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  plan_id uuid not null references membership_plans(id),
  amount numeric(10,2) not null,
  currency text default 'USD',
  payment_method text not null check (payment_method in ('mobile_money', 'bank_transfer', 'paypal')),
  screenshot_url text,
  paypal_order_id text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'refunded')),
  admin_notes text,
  reviewed_by uuid references profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_payment_requests_user on payment_requests(user_id);
create index if not exists idx_payment_requests_status on payment_requests(status);
create index if not exists idx_payment_requests_created on payment_requests(created_at desc);

-- ══════════════════════════════════════════════════════
-- 4. MEMBERSHIPS (active subscriptions)
-- ══════════════════════════════════════════════════════
create table if not exists memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade unique,
  plan_id uuid not null references membership_plans(id),
  payment_request_id uuid references payment_requests(id),
  start_date timestamptz not null default now(),
  end_date timestamptz not null,
  is_active boolean default true,
  auto_renew boolean default false,
  created_at timestamptz default now(),
  constraint valid_dates check (end_date > start_date)
);

create index if not exists idx_memberships_active on memberships(is_active) where is_active = true;

-- ══════════════════════════════════════════════════════
-- 5. EXISTING TABLES (bookings, analytics)
-- ══════════════════════════════════════════════════════
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  preferred_time text,
  duration text,
  notes text,
  status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb,
  timestamp timestamptz default now()
);

create index if not exists idx_analytics_timestamp on analytics_events(timestamp);
create index if not exists idx_analytics_event_name on analytics_events(event_name);

-- ══════════════════════════════════════════════════════
-- 7. ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════
alter table profiles enable row level security;
alter table membership_plans enable row level security;
alter table payment_requests enable row level security;
alter table memberships enable row level security;

-- Profiles: users can read own profile, admins can read all
DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
create policy "Admins can view all profiles"
  on profiles for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

-- Membership plans: anyone can read active plans
DROP POLICY IF EXISTS "Anyone can view active plans" ON membership_plans;
create policy "Anyone can view active plans"
  on membership_plans for select
  using (is_active = true);

-- Payment requests: users can view own, admins can view all
DROP POLICY IF EXISTS "Users can view own payment requests" ON payment_requests;
create policy "Users can view own payment requests"
  on payment_requests for select
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all payment requests" ON payment_requests;
create policy "Admins can view all payment requests"
  on payment_requests for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

DROP POLICY IF EXISTS "Users can insert own payment requests" ON payment_requests;
create policy "Users can insert own payment requests"
  on payment_requests for insert
  with check (auth.uid() = user_id);

-- Memberships: users can view own, admins can view all
DROP POLICY IF EXISTS "Users can view own membership" ON memberships;
create policy "Users can view own membership"
  on memberships for select
  using (auth.uid() = user_id);

DROP POLICY IF EXISTS "Admins can view all memberships" ON memberships;
create policy "Admins can view all memberships"
  on memberships for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- ══════════════════════════════════════════════════════
-- 8. SEED DATA — Membership Plans
-- ══════════════════════════════════════════════════════
insert into membership_plans (name, slug, description, price, currency, duration_days, features) values
(
  'Starter',
  'starter',
  'Perfect for individuals who want access to Stack Advisor tools and premium community resources.',
  29.00,
  'USD',
  30,
  '["Stack Advisor access", "Community forum access", "Email support", "1 project review per month"]'
),
(
  'Professional',
  'professional',
  'Ideal for developers and designers who need advanced Stack Advisor tools, templates, and priority support.',
  79.00,
  'USD',
  30,
  '["All Starter features", "Advanced Stack Advisor tools", "Premium templates & blueprints", "Priority email support", "5 project reviews per month", "Monthly live Q&A sessions"]'
),
(
  'Enterprise',
  'enterprise',
  'For teams and organizations that want full access to every Stack Advisor tool plus dedicated consulting and custom workshops.',
  199.00,
  'USD',
  30,
  '["All Professional features", "Full Stack Advisor access", "Unlimited project reviews", "1-on-1 mentorship calls", "Custom workshop sessions", "Team dashboard & reporting", "White-label certifications", "Dedicated account manager"]'
) on conflict (slug) do nothing;

