-- ─── Fera AI Solutions — Complete Database Schema ───
-- Includes: auth profiles, membership plans, payment requests,
-- memberships, system design tutorials, bookings, analytics.

-- ══════════════════════════════════════════════════════
-- 0. EXTENSIONS
-- ══════════════════════════════════════════════════════
create extension if not exists "pgcrypto";

-- ══════════════════════════════════════════════════════
-- 1. USER PROFILES (syncs with auth.users)
-- ══════════════════════════════════════════════════════
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  avatar_url text,
  is_admin boolean default false,
  role text default 'user' check (role in ('user', 'admin')),
  region text default 'local' check (region in ('local', 'global')),
  created_at timestamptz default now()
);

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1)),
    'user'
  );
  return new;
end;
$$;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ══════════════════════════════════════════════════════
-- 2. MEMBERSHIP PLANS
-- ══════════════════════════════════════════════════════
create table if not exists membership_plans (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  description text not null,
  price numeric(10,2) not null,
  currency text default 'USD',
  duration_days integer not null default 30,
  features jsonb default '[]',
  is_active boolean default true,
  created_at timestamptz default now()
);

-- ══════════════════════════════════════════════════════
-- 3. PAYMENT REQUESTS (screenshot uploads + PayPal)
-- ══════════════════════════════════════════════════════
create table if not exists payment_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade,
  plan_id uuid not null references membership_plans(id),
  amount numeric(10,2) not null,
  currency text default 'USD',
  payment_method text not null check (payment_method in ('mobile_money', 'bank_transfer', 'paypal')),
  screenshot_url text,
  paypal_order_id text,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'refunded')),
  admin_notes text,
  reviewed_by uuid references profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz default now()
);

create index if not exists idx_payment_requests_user on payment_requests(user_id);
create index if not exists idx_payment_requests_status on payment_requests(status);
create index if not exists idx_payment_requests_created on payment_requests(created_at desc);

-- ══════════════════════════════════════════════════════
-- 4. MEMBERSHIPS (active subscriptions)
-- ══════════════════════════════════════════════════════
create table if not exists memberships (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references profiles(id) on delete cascade unique,
  plan_id uuid not null references membership_plans(id),
  payment_request_id uuid references payment_requests(id),
  start_date timestamptz not null default now(),
  end_date timestamptz not null,
  is_active boolean default true,
  auto_renew boolean default false,
  created_at timestamptz default now(),
  constraint valid_dates check (end_date > start_date)
);

create index if not exists idx_memberships_active on memberships(is_active) where is_active = true;

-- ══════════════════════════════════════════════════════
-- 5. SYSTEM DESIGN TUTORIALS (premium content)
-- ══════════════════════════════════════════════════════
create table if not exists system_design_tutorials (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  slug text not null unique,
  description text not null,
  category text not null,
  difficulty text not null check (difficulty in ('beginner', 'intermediate', 'advanced')),
  icon text default '📐',
  content text not null,
  is_premium boolean default true,
  order_index integer default 0,
  created_at timestamptz default now()
);

create index if not exists idx_tutorials_premium on system_design_tutorials(is_premium);
create index if not exists idx_tutorials_order on system_design_tutorials(order_index);

-- ══════════════════════════════════════════════════════
-- 6. EXISTING TABLES (bookings, analytics)
-- ══════════════════════════════════════════════════════
create table if not exists bookings (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  preferred_time text,
  duration text,
  notes text,
  status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb,
  timestamp timestamptz default now()
);

create index if not exists idx_analytics_timestamp on analytics_events(timestamp);
create index if not exists idx_analytics_event_name on analytics_events(event_name);

-- ══════════════════════════════════════════════════════
-- 7. ROW LEVEL SECURITY
-- ══════════════════════════════════════════════════════
alter table profiles enable row level security;
alter table membership_plans enable row level security;
alter table payment_requests enable row level security;
alter table memberships enable row level security;
alter table system_design_tutorials enable row level security;

-- Profiles: users can read own profile, admins can read all
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

create policy "Admins can view all profiles"
  on profiles for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

-- Membership plans: anyone can read active plans
create policy "Anyone can view active plans"
  on membership_plans for select
  using (is_active = true);

-- Payment requests: users can view own, admins can view all
create policy "Users can view own payment requests"
  on payment_requests for select
  using (auth.uid() = user_id);

create policy "Admins can view all payment requests"
  on payment_requests for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "Users can insert own payment requests"
  on payment_requests for insert
  with check (auth.uid() = user_id);

-- Memberships: users can view own, admins can view all
create policy "Users can view own membership"
  on memberships for select
  using (auth.uid() = user_id);

create policy "Admins can view all memberships"
  on memberships for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- Tutorials: any authenticated user can view, but premium content gating is done in app
create policy "Authenticated users can view tutorials"
  on system_design_tutorials for select
  using (auth.role() = 'authenticated');

-- ══════════════════════════════════════════════════════
-- 8. SEED DATA — Membership Plans
-- ══════════════════════════════════════════════════════
insert into membership_plans (name, slug, description, price, currency, duration_days, features) values
(
  'Starter',
  'starter',
  'Perfect for individuals who want access to foundational system design tutorials and premium community resources.',
  29.00,
  'USD',
  30,
  '["Access to basic system design tutorials", "Community forum access", "Email support", "1 project review per month"]'
),
(
  'Professional',
  'professional',
  'Ideal for developers and designers who need in-depth training, advanced templates, and priority support.',
  79.00,
  'USD',
  30,
  '["All Starter features", "Advanced system design tutorials", "Premium templates & blueprints", "Priority email support", "5 project reviews per month", "Monthly live Q&A sessions"]'
),
(
  'Enterprise',
  'enterprise',
  'For teams and organizations that want full access to the entire library plus dedicated consulting and custom workshops.',
  199.00,
  'USD',
  30,
  '["All Professional features", "Full tutorial library access", "Unlimited project reviews", "1-on-1 mentorship calls", "Custom workshop sessions", "Team dashboard & reporting", "White-label certifications", "Dedicated account manager"]'
) on conflict (slug) do nothing;

-- ══════════════════════════════════════════════════════
-- 9. SEED DATA — System Design Tutorials
-- ══════════════════════════════════════════════════════
insert into system_design_tutorials (title, slug, description, category, difficulty, icon, content, is_premium, order_index) values
(
  'Introduction to System Design',
  'intro-to-system-design',
  'Learn the fundamentals of system design, including scalability, reliability, and trade-off analysis.',
  'Fundamentals',
  'beginner',
  '🧠',
  E'## What is System Design?\n\nSystem design is the process of defining the architecture, components, modules, interfaces, and data for a system to satisfy specified requirements.\n\n## Key Concepts\n\n### 1. Scalability\nThe ability of a system to handle growing amounts of work by adding resources.\n\n### 2. Reliability\nThe probability that a system will produce correct outputs up to a given time.\n\n### 3. Availability\nThe proportion of time a system is in a functioning condition.\n\n### 4. Maintainability\nThe ease with which a system can be modified to fix defects or adapt to new requirements.\n\n## Trade-offs\n- Consistency vs. Availability (CAP Theorem)\n- Latency vs. Throughput\n- Performance vs. Scalability',
  false,
  1
),
(
  'Designing a URL Shortener',
  'designing-a-url-shortener',
  'Step-by-step guide to designing a scalable URL shortening service like TinyURL or Bitly.',
  'System Design',
  'beginner',
  '🔗',
  E'## Requirements\n- Generate short unique URLs\n- Redirect to original URL\n- Analytics (click tracking)\n- High availability and low latency\n\n## High-Level Design\n1. **API Gateway** receives requests\n2. **URL Service** generates/retrieves short codes\n3. **Database** stores mappings\n4. **Cache** (Redis) for hot URLs\n5. **Analytics Service** tracks clicks\n\n## Database Schema\n- `urls`: id, short_code, original_url, created_at, expires_at\n- `clicks`: id, url_id, timestamp, user_agent, ip, referrer\n\n## Key Algorithms\n- Base62 encoding for short codes\n- Consistent hashing for sharding',
  false,
  2
),
(
  'Designing a Payment System',
  'designing-a-payment-system',
  'Architecture for a robust, scalable payment processing system with multi-currency support.',
  'System Design',
  'intermediate',
  '💳',
  E'## Requirements\n- Process payments in multiple currencies\n- Handle payment gateway failures\n- Idempotency for retry safety\n- Real-time transaction status updates\n- Audit logging and reconciliation\n\n## Architecture\n1. **Payment Service** — orchestrates payment flow\n2. **Payment Gateway Adapter** — abstracts multiple providers\n3. **Ledger Service** — records all financial transactions\n4. **Reconciliation Service** — matches external statements\n5. **Notification Service** — sends payment confirmations\n\n## Key Design Decisions\n- Use event sourcing for the ledger\n- Implement Saga pattern for distributed transactions\n- Use idempotency keys for retry safety\n- Store events in append-only log',
  true,
  3
),
(
  'Designing a Chat System',
  'designing-a-chat-system',
  'Build a real-time messaging system with presence, history, and multi-device support.',
  'System Design',
  'intermediate',
  '💬',
  E'## Requirements\n- Real-time messaging with low latency\n- Message persistence and history\n- Read receipts and typing indicators\n- Multi-device support\n- Group chats\n\n## Architecture\n1. **WebSocket Gateway** — maintains persistent connections\n2. **Message Service** — routes and persists messages\n3. **Presence Service** — tracks online status\n4. **Notification Service** — push notifications\n5. **History Service** — retrieves past messages\n\n## Data Flow\n1. Client sends message via WebSocket\n2. Gateway publishes to message queue (Kafka/RabbitMQ)\n3. Message Service persists to database\n4. Fan-out to recipients via their WebSocket connections\n5. If offline, push notification is sent',
  true,
  4
),
(
  'Designing a Video Streaming Platform',
  'designing-a-video-streaming-platform',
  'Architecture for a video streaming service like YouTube or Netflix, covering encoding, CDN, and recommendations.',
  'System Design',
  'advanced',
  '🎬',
  E'## Requirements\n- Upload and process videos at scale\n- Adaptive bitrate streaming\n- Global content delivery\n- Search and recommendations\n- User engagement tracking\n\n## Architecture\n1. **Upload Service** — receives and validates uploads\n2. **Transcoding Pipeline** — converts to multiple resolutions\n3. **Content Delivery Network (CDN)** — edge caching\n4. **Metadata Service** — stores video info and thumbnails\n5. **Recommendation Engine** — ML-based suggestions\n6. **Search Service** — Elasticsearch for full-text search\n\n## Key Components\n- **Storage**: Object storage (S3) for raw and processed videos\n- **CDN**: Cache at edge locations\n- **Adaptive Bitrate**: HLS or DASH protocols\n- **Transcoding**: FFmpeg pipeline with queue workers\n\n## Scaling\n- Uploads: Use presigned URLs for direct-to-storage\n- Playback: CDN caching with geographic routing\n- Transcoding: Worker pool with auto-scaling',
  true,
  5
),
(
  'Designing a Social Media Feed',
  'designing-a-social-media-feed',
  'Build a scalable news feed system like Facebook or Twitter with ranking and real-time updates.',
  'System Design',
  'advanced',
  '📱',
  E'## Requirements\n- Aggregate posts from followed users\n- Rank feed by relevance\n- Real-time updates for new posts\n- Support for different content types (text, images, video)\n- Low latency feed loading\n\n## Architecture\n### Fan-out on Write\n- When a user publishes, push to followers\' feeds\n- Pros: Fast reads; Cons: Hot followers issue\n\n### Fan-out on Read\n- Pull and merge posts on feed load\n- Pros: No hot follower issue; Cons: Slower reads\n\n### Hybrid Approach\n- Use fan-out for regular users\n- Use pull for celebrities with millions of followers\n\n## Key Technologies\n- **Cache**: Redis for pre-computed feeds\n- **Database**: Cassandra for scalable writes\n- **Ranking**: ML model for relevance scoring\n- **Real-time**: WebSocket for live updates',
  true,
  6
) on conflict (slug) do nothing;

