create table if not exists bookings (
  id bigint generated by default as identity primary key,
  name text,
  email text not null,
  preferred_time text,
  duration text,
  notes text,
  status text default 'Pending',
  created_at timestamptz default now()
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  payload jsonb,
  timestamp timestamptz default now()
);

create index if not exists idx_analytics_timestamp on analytics_events(timestamp);
create index if not exists idx_analytics_event_name on analytics_events(event_name);

