// ─── Project Types & Business Feature Recommendations ──
import type { ProjectType } from "./types";

export const projectTypes: ProjectType[] = [
  {
    id: "lms",
    label: "LMS / Learning Platform",
    icon: "🎓",
    description:
      "A learning management system with courses, quizzes, progress tracking, video lectures, and student management.",
    businessFeatures: [
      "Course creation & management dashboard",
      "Video lecture hosting with progress tracking",
      "Quiz & assessment engine with auto-grading",
      "Student enrollment & cohort management",
      "Certificates & completion tracking",
      "Course ratings & reviews system",
      "Discussion forums & Q&A",
      "Live session scheduling (Zoom/Meet integration)",
      "Assignment submission & grading",
      "Gamification (badges, leaderboards, XP)",
      "Content drip scheduling",
      "Multi-instructor support with revenue splits",
    ],
  },
  {
    id: "ecommerce",
    label: "E-Commerce / Marketplace",
    icon: "🛒",
    description:
      "An online store or marketplace with product listings, cart, checkout, payments, and order management.",
    businessFeatures: [
      "Product catalog with categories & variants",
      "Shopping cart & wishlist",
      "Secure checkout with multiple payment gateways",
      "Order tracking & management",
      "Inventory management & stock alerts",
      "Seller/vendor dashboard (for marketplaces)",
      "Product reviews & ratings",
      "Discount coupons & promotional campaigns",
      "Shipping & delivery tracking",
      "Abandoned cart recovery",
      "Multi-currency & multi-language support",
      "Returns & refunds management",
    ],
  },
  {
    id: "saas",
    label: "SaaS Platform",
    icon: "☁️",
    description:
      "A subscription-based software service with user accounts, billing, and scalable cloud infrastructure.",
    businessFeatures: [
      "User onboarding wizard & tutorials",
      "Subscription & billing management (Stripe/PayPal)",
      "Multi-tenant architecture",
      "Role-based access control (RBAC)",
      "Usage analytics & dashboards",
      "API access & developer portal",
      "Team/collaboration features",
      "White-labeling options",
      "Feature flags & A/B testing",
      "Automated email notifications",
      "Data export & reporting",
      "SSO & enterprise authentication",
    ],
  },
  {
    id: "social",
    label: "Social Media / Community",
    icon: "💬",
    description:
      "A social platform with user profiles, posts, feeds, messaging, and community features.",
    businessFeatures: [
      "User profiles with avatars & bios",
      "News feed with algorithmic or chronological sorting",
      "Posts, likes, comments & shares",
      "Direct messaging & chat",
      "Groups & communities",
      "Content moderation tools",
      "Notifications (push & email)",
      "Stories & temporary content",
      "Follow/unfollow system",
      "Hashtags & content discovery",
      "Live streaming capabilities",
      "Analytics for content creators",
    ],
  },
  {
    id: "erp",
    label: "Enterprise ERP System",
    icon: "🏢",
    description:
      "An enterprise resource planning system integrating finance, HR, inventory, operations, and reporting.",
    businessFeatures: [
      "Financial management (GL, AP, AR, reconciliation)",
      "Human resources & payroll management",
      "Inventory & supply chain management",
      "Project management & timesheets",
      "Customer relationship management (CRM)",
      "Purchase order & procurement",
      "Asset management",
      "Business intelligence dashboards",
      "Multi-branch/branch management",
      "Compliance & audit trails",
      "Approval workflows",
      "Document management system",
    ],
  },
  {
    id: "fintech",
    label: "Fintech / Payment Platform",
    icon: "💳",
    description:
      "A financial technology platform handling payments, transfers, wallets, and financial data.",
    businessFeatures: [
      "Digital wallet & balance management",
      "Peer-to-peer transfers",
      "Bill payments & utilities",
      "Transaction history & receipts",
      "Mobile money integration (Chapa, Telebirr)",
      "Bank transfer reconciliation",
      "Multi-currency support",
      "Recurring payments & subscriptions",
      "KYC & identity verification",
      "Fraud detection & prevention",
      "Admin approval workflows for large transactions",
      "Financial reporting & analytics",
    ],
  },
  {
    id: "healthcare",
    label: "Healthcare / Telemedicine",
    icon: "🏥",
    description:
      "A healthcare platform with patient management, appointments, telemedicine, and medical records.",
    businessFeatures: [
      "Patient registration & medical records",
      "Appointment scheduling & reminders",
      "Video consultations (telemedicine)",
      "E-prescriptions & pharmacy integration",
      "Lab results & diagnostic uploads",
      "HIPAA/GDPR compliance features",
      "Doctor availability & scheduling",
      "Payment & insurance processing",
      "Health analytics & reporting",
      "Patient portal & self-service",
      "Multi-clinic/hospital management",
      "Emergency alert system",
    ],
  },
  {
    id: "realestate",
    label: "Real Estate Platform",
    icon: "🏠",
    description:
      "A real estate platform with property listings, virtual tours, agent management, and client inquiries.",
    businessFeatures: [
      "Property listing with images & virtual tours",
      "Advanced search & filters (location, price, type)",
      "Interactive maps & neighborhood data",
      "Agent/broker profiles & management",
      "Mortgage calculator & affordability tools",
      "Property comparison tool",
      "Inquiry & appointment booking",
      "Favorite/saved properties",
      "Market analytics & price trends",
      "Virtual open house scheduling",
      "Rental management & lease tracking",
      "Document signing & workflow",
    ],
  },
  {
    id: "content",
    label: "Content / Media Platform",
    icon: "📺",
    description:
      "A content platform for blogs, videos, podcasts, or digital media with subscriptions and monetization.",
    businessFeatures: [
      "Content management system (CMS)",
      "Video/audio streaming & hosting",
      "Subscription & paywall system",
      "Content categorization & tags",
      "SEO optimization tools",
      "Reader/viewer analytics",
      "Comments & community engagement",
      "Newsletter & email digests",
      "Ad management & revenue tracking",
      "Multi-author support",
      "Content scheduling & publishing workflow",
      "Membership tiers & exclusive content",
    ],
  },
  {
    id: "booking",
    label: "Booking / Reservation System",
    icon: "📅",
    description:
      "A booking platform for services, hotels, restaurants, or appointments with availability management.",
    businessFeatures: [
      "Service/resource catalog",
      "Real-time availability calendar",
      "Online booking & reservation",
      "Payment at booking or deposit",
      "Automated confirmation & reminders",
      "Staff/resource management",
      "Cancellation & rescheduling policy",
      "Waitlist management",
      "Review & rating system",
      "Multi-location management",
      "POS integration for on-site payments",
      "Analytics & revenue reporting",
    ],
  },
];
