// ─── Recommended Stacks by Project Type ──────────────
import type { RecommendedStack } from "./types";

export const recommendedStacks: RecommendedStack[] = [
  {
    projectType: "lms",
    name: "Next.js + Supabase (Recommended)",
    description:
      "Full-stack Next.js with Supabase for auth, database, and storage. Bunny.net for video hosting. Deploy on Vercel.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "bunny",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "lms",
    name: "React + Node.js (Alternative)",
    description:
      "React frontend with Node.js/Express backend. MongoDB for flexible course data. Firebase auth.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "mongodb",
      auth: "firebase_auth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "paypal",
      email: "sendgrid",
      cache: "redis_self",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "ecommerce",
    name: "Next.js + Supabase + Stripe",
    description:
      "Next.js storefront with Supabase backend and Stripe/Chapa for payments. Bunny CDN for product images.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "cloudinary",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "saas",
    name: "Next.js + Supabase + Vercel",
    description:
      "Production-ready SaaS with Next.js, Supabase auth/DB, Stripe subscriptions, and Vercel deployment.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "stripe",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "intermediate",
  },
  {
    projectType: "erp",
    name: "Next.js + Django + PostgreSQL",
    description:
      "Enterprise ERP with Django admin panel, Next.js frontend, PostgreSQL database, and Docker deployment on Ethiopian VPS.",
    selections: {
      frontend: "nextjs",
      backend: "django",
      database: "postgresql",
      auth: "nextauth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "docker_vps",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_self",
      testing: "jest",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "advanced",
  },
  {
    projectType: "fintech",
    name: "Next.js + FastAPI + PostgreSQL",
    description:
      "High-performance fintech backend with FastAPI, Next.js frontend, PostgreSQL with strong consistency, and Chapa/Telebirr payments.",
    selections: {
      frontend: "nextjs",
      backend: "python_fastapi",
      database: "postgresql",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "advanced",
  },

  // ─── SOCIAL / COMMUNITY ──────────────────────────────
  {
    projectType: "social",
    name: "Next.js + Supabase + Vercel (Recommended)",
    description:
      "Full-stack Next.js with Supabase real-time subscriptions for live feeds, chat, and notifications. Supabase Storage for avatars & media. Deploy on Vercel.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "social",
    name: "React + Node.js + MongoDB (Alternative)",
    description:
      "React frontend with Node.js/Express backend. MongoDB for flexible social graph data. Firebase Auth for quick signup. Deploy on Railway + Netlify.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "mongodb",
      auth: "firebase_auth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "paypal",
      email: "sendgrid",
      cache: "redis_self",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },

  // ─── HEALTHCARE / TELEMEDICINE ──────────────────────
  {
    projectType: "healthcare",
    name: "Next.js + Django + PostgreSQL (Recommended)",
    description:
      "Enterprise healthcare platform with Django admin panel for patient/doctor management, PostgreSQL for medical records, and Docker VPS for Ethiopian data residency compliance.",
    selections: {
      frontend: "nextjs",
      backend: "django",
      database: "postgresql",
      auth: "nextauth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "docker_vps",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_self",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "advanced",
  },
  {
    projectType: "healthcare",
    name: "Next.js + FastAPI + Supabase (Alternative)",
    description:
      "Lightweight telemedicine platform with FastAPI async backend for video consultation scheduling, Supabase for auth/DB/storage, and Vercel deployment.",
    selections: {
      frontend: "nextjs",
      backend: "python_fastapi",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },

  // ─── REAL ESTATE ────────────────────────────────────
  {
    projectType: "realestate",
    name: "Next.js + Supabase + Cloudinary (Recommended)",
    description:
      "Next.js property listing platform with Supabase for structured data & auth, Cloudinary for image optimization & virtual tours, and Vercel deployment.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "cloudinary",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "realestate",
    name: "React + Node.js + PostgreSQL (Alternative)",
    description:
      "React frontend with Node.js/Express backend and PostgreSQL for spatial queries (location-based search). Perfect for advanced property filtering & maps.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "postgresql",
      auth: "nextauth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "paypal",
      email: "sendgrid",
      cache: "redis_upstash",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },

  // ─── CONTENT / MEDIA PLATFORM ───────────────────────
  {
    projectType: "content",
    name: "Next.js + Supabase + Bunny CDN (Recommended)",
    description:
      "Next.js content platform with Supabase for auth/DB, Bunny.net for video streaming & CDN, and Vercel for global deployment. Optimized for Ethiopian viewers with South African PoPs.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "bunny",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "content",
    name: "React + Node.js + Supabase (Alternative)",
    description:
      "React frontend with Node.js/Express backend and Supabase for flexible content storage. Cloudinary for image CDN. Deploy on Netlify + Railway.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "stripe",
      email: "sendgrid",
      cache: "redis_self",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "beginner",
  },

  // ─── BOOKING / RESERVATION SYSTEM ──────────────────
  {
    projectType: "booking",
    name: "Next.js + Supabase + Chapa (Recommended)",
    description:
      "Next.js booking platform with Supabase for real-time availability tracking, auth, and storage. Chapa for Ethiopian mobile money payments. Vercel deployment.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "booking",
    name: "React + Node.js + PostgreSQL + Stripe (Alternative)",
    description:
      "React booking engine with Node.js/Express backend, PostgreSQL for structured reservation data, and Stripe for international card payments. Deploy on Railway + Netlify.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "postgresql",
      auth: "nextauth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "stripe",
      email: "sendgrid",
      cache: "redis_upstash",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },
];
