// ─── Recommended Stacks by Project Type ──────────────
import type { RecommendedStack } from "./types";

export const recommendedStacks: RecommendedStack[] = [
  {
    projectType: "lms",
    name: "Next.js + Supabase (Recommended)",
    description:
      "Full-stack Next.js with Supabase for auth, database, and storage. Bunny.net for video hosting. Deploy on Vercel.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "bunny",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "lms",
    name: "React + Node.js (Alternative)",
    description:
      "React frontend with Node.js/Express backend. MongoDB for flexible course data. Firebase auth.",
    selections: {
      frontend: "vite_react",
      backend: "node",
      database: "mongodb",
      auth: "firebase_auth",
      storage: "cloudinary",
      deploy_frontend: "netlify",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "paypal",
      email: "sendgrid",
      cache: "redis_self",
      testing: "jest",
      monitoring: "posthog",
    },
    isPrimary: false,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "ecommerce",
    name: "Next.js + Supabase + Stripe",
    description:
      "Next.js storefront with Supabase backend and Stripe/Chapa for payments. Bunny CDN for product images.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "cloudinary",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "low",
    difficulty: "intermediate",
  },
  {
    projectType: "saas",
    name: "Next.js + Supabase + Vercel",
    description:
      "Production-ready SaaS with Next.js, Supabase auth/DB, Stripe subscriptions, and Vercel deployment.",
    selections: {
      frontend: "nextjs",
      backend: "nextjs_api",
      database: "supabase_db",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "vercel",
      cicd: "github_actions",
      payment: "stripe",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "intermediate",
  },
  {
    projectType: "erp",
    name: "Next.js + Django + PostgreSQL",
    description:
      "Enterprise ERP with Django admin panel, Next.js frontend, PostgreSQL database, and Docker deployment on Ethiopian VPS.",
    selections: {
      frontend: "nextjs",
      backend: "django",
      database: "postgresql",
      auth: "nextauth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "docker_vps",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_self",
      testing: "jest",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "advanced",
  },
  {
    projectType: "fintech",
    name: "Next.js + FastAPI + PostgreSQL",
    description:
      "High-performance fintech backend with FastAPI, Next.js frontend, PostgreSQL with strong consistency, and Chapa/Telebirr payments.",
    selections: {
      frontend: "nextjs",
      backend: "python_fastapi",
      database: "postgresql",
      auth: "supabase_auth",
      storage: "supabase_storage",
      deploy_frontend: "vercel",
      deploy_backend: "railway",
      cicd: "github_actions",
      payment: "chapa",
      email: "resend",
      cache: "redis_upstash",
      testing: "playwright",
      monitoring: "sentry",
    },
    isPrimary: true,
    cost: "medium",
    difficulty: "advanced",
  },
];
